version: '2.4'

volumes:
  web.ssl
  web.www

services:
  proxy:
    build: proxy
    restart: always
    volumes:
      - web.ssl:/etc/letsencrypt
      - web.www:/var/www
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: "2m"
        max-file: "5"

